name: Build and Deploy Facsciences

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build React Project
    runs-on: ubuntu-latest

    steps:
      # Récupérer le code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Installer Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Créer le fichier .env à partir des Secrets
      - name: Setup .env
        run: |
          echo "VITE_BACKEND_PREINSCRIPTION=${{ secrets.VITE_BACKEND_PREINSCRIPTION }}" >> .env
          echo "VITE_BACKEND_FACSCIENCES=${{ secrets.VITE_BACKEND_FACSCIENCES }}" >> .env
          echo "VITE_BACKEND_WEBSERVICES=${{ secrets.VITE_BACKEND_WEBSERVICES }}" >> .env

      # Installer les dépendances
      - name: Install dependencies
        run: npm install

      # Tests optionnels
      - name: Run tests (optional)
        run: npm test --if-present

      # Build React
      - name: Build project
        run: npm run build

      # Sauvegarder le build comme artefacts
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: react-build
          path: dist

  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Télécharger le build du job précédent
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: react-build
          path: build

      # Nettoyer le dossier cible sur le serveur pour eviter les erreurs
      - name: Clean target folder
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            rm -rf /var/www/facscience/*

      # Copier le build dans le dossier cible
      - name: Copy build to folder
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          source: "build/*"
          target: "/var/www/facscience"
          strip_components: 1
