name: Test SSH Copy

on:
  push:
    branches:
      - main

jobs:
  test-copy:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Récupérer le code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Tester la copie via SCP
      - name: Copy test file to VPS home
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          source: ".github/workflows/test.txt"   # crée un pett fichier test.txt ici .
          target: "/home/sciadm/test.txt"      # copie le fichier dans le home de l'utilisateur
          strip_components: 0
          debug: true
